<a name="banner-image-<?= $this->paragraph->id ?>-<?= $this->banner->id ?>"
<?php if ( $this->banner->linkTo ): ?>

   href="<?= $this->escapeHtmlAttr( $this->banner->linkTo ) ?>"
<?php if ( $this->banner->linkTarget ): ?>

   target="<?= $this->escapeHtmlAttr( $this->banner->linkTarget ) ?>"
<?php endif ?>
<?php endif ?>

   class="banner-image-link" />
    <img alt="<?= $this->escapeHtmlAttr( $this->banner->alternate ) ?>"
<?php if ( $this->banner->width ): ?>

         width="<?= (int) $this->banner->width ?>"
<?php endif ?>
<?php if ( $this->banner->height ): ?>

         height="<?= (int) $this->banner->height ?>"
<?php endif ?>

         src="<?= $this->escapeHtmlAttr( $this->banner->url ) ?>" />
</a>
