<?php $banner = $this->paragraph->findBanner(); if ( $banner ): ?>
<div class="banner banner-<?= $banner->type ?>">
        <?= $this->partial( $banner->viewPartial, array(
            'banner'    => $banner,
            'paragraph' => $this->paragraph,
        ) ) ?>
    </div>
<?php else: ?>

    <div class="banner banner-not-found">
        <a name="banner-not-found-<?= $this->paragraph->id ?>"
<?php if ( $this->isAllowed( 'banner', 'view' ) ): ?>

           href="/app/<?= $this->locale() ?>/admin/banner/set/list"
<?php endif ?>

           class="banner-not-found-link"><?=
            $this->translate( 'banner.paragraph.notFound', 'banner' ) ?></a>
    </div>
<?php endif ?>
