<?php $banner = $this->paragraph->findBanner(); if ( $banner ): ?>
<div class="banner banner-<?= $banner->type ?>">
        <?= $this->partial( $banner->viewPartial, array(
            'banner'    => $banner,
            'paragraph' => $this->paragraph,
        ) ) ?>
    </div>
<?php else: ?>

    <div class="banner banner-image banner-not-found">
        <a name="banner-image-<?= $this->paragraph->id ?>"
<?php if ( $this->isAllowed( 'banner', 'view' ) ): ?>

           href="/app/<?= $this->locale() ?>/admin/banner/set/list"
<?php endif ?>

           class="banner-image-link">
            <img alt="<?= $this->escapeHtmlAttr( $this->translate( 'banner.paragraph.notFound', 'banner' ) ) ?>"
                 src="/images/modules/Banner/not-found.png" />
        </a>
    </div>
<?php endif ?>
